# Generated by Django 4.2.14 on 2024-08-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='Job description: \n \n Responsibility: \n \n Qualifications: \n \n Benefits: ', max_length=1000),
        ),
    ]
