# Generated by Django 4.2.14 on 2024-08-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Benefits',
            field=models.TextField(default='Benefits: \n \n', max_length=10000),
        ),
        migrations.AddField(
            model_name='job',
            name='Qualifications',
            field=models.TextField(default='Qualifications: \n \n ', max_length=10000),
        ),
        migrations.AddField(
            model_name='job',
            name='Responsibility',
            field=models.TextField(default=' Responsibility: \n \n', max_length=10000),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=' description: \n \n', max_length=10000),
        ),
    ]
