# Generated by Django 4.2.14 on 2024-08-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_benefits_job_qualifications_job_responsibility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Benefits',
            new_name='benefits',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Qualifications',
            new_name='qualifications',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Responsibility',
            new_name='responsibility',
        ),
    ]
