# Generated by Django 4.2.14 on 2024-08-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_job_benefits_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sulg',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
