# Generated by Django 4.2.14 on 2024-08-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='sulg',
            new_name='slug',
        ),
    ]
