# Generated by Django 4.2.14 on 2024-08-05 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='apply_job', to='job.job'),
            preserve_default=False,
        ),
    ]
