# Generated by Django 4.2.14 on 2024-08-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='caret_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
